config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "contactos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contacto.rb
class Contacto < ApplicationRecord
    paginates_per 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: %i[ show edit update destroy ]

  # GET /contactos or /contactos.json
  def index
    @contactos = Contacto.all
    @contactos = Kaminari.paginate_array(@contactos).page(params[:page])

  end

  # GET /contactos/1 or /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos or /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully created." }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1 or /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully updated." }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1 or /contactos/1.json
  def destroy
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to contactos_url, notice: "Contacto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :correo, :asunto, :mensaje)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/contactos/_contacto.html.erb
<h1>Datos Contacto</h1>
<div id="<%= dom_id contacto %>" class ="form-control">
  <p>
    <strong>Nombre:</strong>
    <%= contacto.nombre %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= contacto.correo %>
  </p>

  <p>
    <strong>Asunto:</strong>
    <%= contacto.asunto %>
  </p>

  <p>
    <strong>Mensaje:</strong>
    <%= contacto.mensaje %>
  </p>

</div>

app/views/contactos/_form.html.erb
<%= form_with(model: contacto) do |form| %>
  <% if contacto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
        <% contacto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class ="row">
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class ="row">
    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo , class: "form-control"%>
  </div>

  <div class ="row">
    <%= form.label :asunto, style: "display: block" %>
    <%= form.text_field :asunto , class: "form-control"%>
  </div>

  <div class ="row">
    <%= form.label :mensaje, style: "display: block" %>
    <%= form.text_area :mensaje , class: "form-control"%>
  </div>
  <br>
   <div>
      <%= form.submit "Grabar Datos"%>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editando Contacto</h1>

<%= render "form", contacto: @contacto %>

<br>

<div>
  <%= link_to "Ver datos contacto", @contacto %> |
  <%= link_to "Volver", contactos_path %>
</div>

app/views/contactos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contactos</h1>

<%= paginate @contactos %>
<div id="contactos">
  <table class="table  table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
      <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Asunto</th>
        <th>Mensaje</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
<tbody>

  <% @contactos.each do |contacto| %>
    <tr>
      <td><%= contacto.nombre %></td>
      <td><%= contacto.correo %></td>
      <td><%= contacto.asunto %></td>
      <td><%= contacto.mensaje %></td>
      <td><%= link_to "Ver", contacto %></td>
      <td><%= link_to "Editar", edit_contacto_path(contacto) %></td>
      <td><%= link_to "Eliminar", contacto, method: :delete, data:{confirm: '¿Está seguro de Eliminar?'} %></td>
    </tr>
    
  <% end %>
  </tbody>
  
  </table>
</div>
<%=paginate @contactos %>
<%= page_entries_info @contactos, entry_name: 'item' %>
<br>
<%= link_to "New contacto", new_contacto_path %>

app/views/contactos/new.html.erb
<h1>New contacto</h1>

<%= render "form", contacto: @contacto %>

<br>

<div>
  <%= link_to "Back to contactos", contactos_path %>
</div>

app/views/contactos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contacto %>

<div>
  <%= link_to "Edit this contacto", edit_contacto_path(@contacto) %> |
  <%= link_to "Back to contactos", contactos_path %>

  <%= button_to "Destroy this contacto", @contacto, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freshfish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  
    
    </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark text-white">
    <div class="container">
            <a class="navbar-brand" href="#">
             <%= image_tag("logo.png", :alt => "Logo Freshfish", :style=>"width:80px;", :class=>"rounded-pill bg-light") %>
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"    aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button> 
        <div class="collapse navbar-collapse"      id="navbarTogglerDemo03">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="#inicio">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#Carrito">Carrito de compras</a>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#contacto">Contacto</a>
                </li>
                <a href="#">
                  <i class="fa-brands fa-whatsapp fa-2x mx-2"></i>
                </a>
                <a href="#">
                  <i class="fa-brands fa-facebook fa-2x mx-2"></i>
                </a>
                <a href="#">
                  <i class="fa-brands fa-instagram-square fa-2x mx-2"></i>
                </a>
                <a href="#">
                  <i class="fa-solid fa-user fa-2x mx-2"></i>
                </a>          
                
            </ul>
        </div>       
    </div>
    </nav>
    
    <div class ="container">
    <i class="fas fa-arrow-alt-circle-left"></i>
      <%= yield %>
    <div>
  </body>
</html>